*OLS*

In [ ]:
X= 2*np.random.rand(1000,1)
y=4+3*X+np.random.randn(1000,1)
y_clean = 4 + 3 * X

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [ ]:
model.fit(X.reshape((-1, 1)),y.reshape((-1, 1)))

LinearRegression()

In [ ]:
model.coef_

array([[2.96373159]])

In [ ]:
model.intercept_

array([4.1036951])

*GD*

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from matplotlib import pyplot as plt

In [ ]:
X= 2*np.random.rand(1000,1)
y=4+3*X+np.random.randn(1000,1)
y_clean = 4 + 3 * X

In [ ]:
GD_model = SGDRegressor(max_iter=10, eta0=0.001)
GD_model.fit(X, y.squeeze())

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1548: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(eta0=0.001, max_iter=10)

In [ ]:
y_hat = GD_model.predict(X)

In [ ]:
GD_model.intercept_, GD_model.coef_

(array([3.15475978]), array([3.36658193]))

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y, y_hat)

1.2717948000372887

In [ ]:
GD_model.n_iter_no_change

5